[11:31:42] [DEBUG] Running client sanity checks...
[11:31:44] [DEBUG] No setup function found in play
[11:31:44] [DEBUG] Found extension class Music in play: Attempting to load
[11:31:44] [DEBUG] Added callback: Music._menu
[11:31:44] [DEBUG] Added callback: Music._pause
[11:31:44] [DEBUG] Added callback: Music._resume
[11:31:44] [DEBUG] Added callback: Music._skip
[11:31:44] [DEBUG] Added callback: Music._stop
[11:31:44] [DEBUG] Added callback: Music.play
[11:31:44] [DEBUG] Loaded Extension: play
[11:31:45] [DEBUG] No setup function found in askbard
[11:31:45] [DEBUG] Found extension class Bard in askbard: Attempting to load
[11:31:45] [DEBUG] Added callback: Bard._askbard
[11:31:45] [DEBUG] Added callback: Bard._endbard
[11:31:45] [DEBUG] Added callback: Bard.set_bard_channel
[11:31:45] [DEBUG] Loaded Extension: askbard
[11:31:45] [DEBUG] No setup function found in noi_chu
[11:31:45] [DEBUG] Found extension class NoiChu in noi_chu: Attempting to load
[11:31:45] [DEBUG] Added callback: NoiChu._reset
[11:31:45] [DEBUG] Added callback: NoiChu._world_setup
[11:31:45] [DEBUG] Loaded Extension: noi_chu
[11:31:45] [DEBUG] No setup function found in db_refesh
[11:31:45] [DEBUG] Found extension class Database in db_refesh: Attempting to load
[11:31:45] [DEBUG] Loaded Extension: db_refesh
[11:31:45] [DEBUG] No setup function found in help
[11:31:45] [DEBUG] Found extension class Help in help: Attempting to load
[11:31:45] [DEBUG] Added callback: Help.help
[11:31:45] [DEBUG] Loaded Extension: help
[11:31:45] [DEBUG] Loaded Extension: interactions.ext.jurigged
[11:31:45] [DEBUG] Added callback: __join
[11:31:45] [DEBUG] Added callback: __leave
[11:31:45] [DEBUG] Added callback: _about
[11:31:45] [DEBUG] Added callback: _refresh
[11:31:45] [DEBUG] Added callback: _setup
[11:31:45] [DEBUG] Added callback: on_start
[11:31:45] [DEBUG] 6 callbacks have been loaded from __main__.
[11:31:45] [DEBUG] Added callback: _disconnect
[11:31:45] [DEBUG] Added callback: _on_websocket_ready
[11:31:45] [DEBUG] Added callback: on_autocomplete_completion
[11:31:45] [DEBUG] Added callback: on_autocomplete_error
[11:31:45] [DEBUG] Added callback: on_command_completion
[11:31:45] [DEBUG] Added callback: on_command_error
[11:31:45] [DEBUG] Added callback: on_component_completion
[11:31:45] [DEBUG] Added callback: on_component_error
[11:31:45] [DEBUG] Added callback: on_error
[11:31:45] [DEBUG] Added callback: on_modal_completion
[11:31:45] [DEBUG] Added callback: on_modal_error
[11:31:45] [DEBUG] Added callback: on_resume
[11:31:45] [DEBUG] 12 callbacks have been loaded from Client.
[11:31:45] [DEBUG] Attempting to login
[11:31:45] [DEBUG] Caching ingested rate limit data for: 78bb8553d9352a5a2f89f9def401287a
[11:31:45] [DEBUG] GET /users/@me Has exhausted its ratelimit (1000)! Locking route for 0.001 seconds
[11:31:45] [DEBUG] GET /users/@me Received 200 :: [0/1000 calls remaining]
[11:31:46] [DEBUG] Caching ingested rate limit data for: d28a133af187e91d71d96a223467ce49
[11:31:46] [DEBUG] GET /oauth2/applications/@me Has exhausted its ratelimit (1000)! Locking route for 0.001 seconds
[11:31:46] [DEBUG] GET /oauth2/applications/@me Received 200 :: [0/1000 calls remaining]
[11:31:46] [WARNING] Setting sync_ext to True by default for syncing changes
[11:31:46] [INFO] Loading jurigged
[11:31:46] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\Main.py
[11:31:46] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\embed.py
[11:31:46] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\play.py
[11:31:46] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\askbard.py
[11:31:46] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\noi_chu.py
[11:31:46] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\db_refesh.py
[11:31:46] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\help.py
[11:31:46] [DEBUG] GET /gateway Received 200 :: [1/1 calls remaining]
[11:31:46] [INFO] Shard ID 0 | Starting Shard
[11:31:46] [INFO] Shard ID 0 | Shard is attempting to connect to gateway...
[11:31:46] [DEBUG] Shard ID 0 | Identification payload sent to gateway, requesting intents: 3407613
[11:31:47] [INFO] Shard ID 0 | Gateway connection established
[11:31:47] [DEBUG] Shard ID 0 | Session ID: 7eb95f835139abd8965312b93fb5d112 Trace: ['["gateway-prd-us-east1-b-wtbs",{"micros":129214,"calls":["id_created",{"micros":1343,"calls":[]},"session_lookup_time",{"micros":9224,"calls":[]},"session_lookup_finished",{"micros":17,"calls":[]},"discord-sessions-prd-2-22",{"micros":117540,"calls":["start_session",{"micros":78396,"calls":["discord-api-dc69f8484-zn8h5",{"micros":70111,"calls":["get_user",{"micros":9685},"get_guilds",{"micros":11800},"send_scheduled_deletion_message",{"micros":15},"guild_join_requests",{"micros":275},"authorized_ip_coro",{"micros":15}]}]},"starting_guild_connect",{"micros":62,"calls":[]},"presence_started",{"micros":549,"calls":[]},"guilds_started",{"micros":150,"calls":[]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":38355,"calls":[]},"connect_finished",{"micros":38360,"calls":[]},"build_ready",{"micros":20,"calls":[]},"clean_ready",{"micros":1,"calls":[]},"optimize_ready",{"micros":1,"calls":[]},"split_ready",{"micros":0,"calls":[]}]}]}]']
[11:31:47] [DEBUG] Dispatching Event: websocket_ready
[11:31:47] [DEBUG] Dispatching Event: guild_join
[11:31:47] [DEBUG] Sending heartbeat every 41.25 seconds
[11:31:47] [DEBUG] Sending data to websocket: {"op": 1, "d": 2}
[11:31:47] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[11:31:47] [DEBUG] Dispatching Event: guild_join
[11:31:47] [DEBUG] Dispatching Event: guild_join
[11:31:47] [DEBUG] Dispatching Event: guild_join
[11:31:47] [DEBUG] Dispatching Event: guild_join
[11:31:47] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[11:31:47] [DEBUG] Caching ingested rate limit data for: dd84d9818020c27975c0d5ab4a794d44
[11:31:47] [DEBUG] GET /applications/{application_id}/commands Has exhausted its ratelimit (1000)! Locking route for 0.001 seconds
[11:31:47] [DEBUG] GET /applications/{application_id}/commands Received 200 :: [0/1000 calls remaining]
[11:31:47] [DEBUG] Waiting for bucket dd84d9818020c27975c0d5ab4a794d44 to unlock.
[11:31:48] [DEBUG] Caching ingested rate limit data for: dd84d9818020c27975c0d5ab4a794d44
[11:31:48] [DEBUG] GET /applications/{application_id}/commands Has exhausted its ratelimit (1000)! Locking route for 0.001 seconds
[11:31:48] [DEBUG] GET /applications/{application_id}/commands Received 200 :: [0/1000 calls remaining]
[11:31:48] [DEBUG] 0 is already up-to-date with 15 commands.
[11:31:48] [DEBUG] Sync of 1 scopes took 0.8043782000022475 seconds
[11:31:48] [DEBUG] Dispatching Event: startup
[11:31:48] [DEBUG] Sending data to websocket: {"op": 3, "d": {"since": 1702960308143, "activities": [{"name": "/help for helpful", "type": 0}], "status": "idle", "afk": false}}
[11:31:50] [ERROR] Jurigged encountered an error
Traceback (most recent call last):
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 493, in _process_child_correspondence
    orig.apply_correspondence(
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 704, in apply_correspondence
    new_obj = self.reevaluate(corr.new.node, glb)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 801, in reevaluate
    conform(self.get_object(), new_obj)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\codefind\registry.py", line 118, in conform
    self.conform(obj1, obj2.__code__)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\codefind\registry.py", line 123, in conform
    fv1 = obj1.__code__.co_freevars
          ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '__code__'
[11:31:50] [DEBUG] Update __main__:1
[11:32:01] [ERROR] Jurigged encountered an error
Traceback (most recent call last):
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\live.py", line 104, in refresh
    cf.refresh()
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 1120, in refresh
    cf = CodeFile(
         ^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 1034, in __init__
    tree = ast.parse(self.saved)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: source code string cannot contain null bytes
[11:32:08] [ERROR] Jurigged encountered an error
Traceback (most recent call last):
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 493, in _process_child_correspondence
    orig.apply_correspondence(
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 704, in apply_correspondence
    new_obj = self.reevaluate(corr.new.node, glb)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 801, in reevaluate
    conform(self.get_object(), new_obj)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\codefind\registry.py", line 118, in conform
    self.conform(obj1, obj2.__code__)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\codefind\registry.py", line 123, in conform
    fv1 = obj1.__code__.co_freevars
          ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '__code__'
[11:32:08] [DEBUG] Update __main__:1
[11:32:28] [DEBUG] Sending data to websocket: {"op": 1, "d": 6}
[11:32:28] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[11:32:28] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[11:32:28] [ERROR] Jurigged encountered an error
Traceback (most recent call last):
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\live.py", line 104, in refresh
    cf.refresh()
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 1118, in refresh
    new_source = self.read_source()
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 1065, in read_source
    source = f.read()
             ^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1258.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 1880: character maps to <undefined>
[11:33:09] [DEBUG] Sending data to websocket: {"op": 1, "d": 6}
[11:33:09] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[11:33:09] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[11:33:39] [ERROR] Jurigged encountered an error
Traceback (most recent call last):
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\live.py", line 104, in refresh
    cf.refresh()
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 1118, in refresh
    new_source = self.read_source()
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 1065, in read_source
    source = f.read()
             ^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1258.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 1880: character maps to <undefined>
[11:33:50] [DEBUG] Sending data to websocket: {"op": 1, "d": 6}
[11:33:50] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[11:33:51] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[11:34:32] [DEBUG] Sending data to websocket: {"op": 1, "d": 6}
[11:34:32] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[11:34:32] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[11:34:50] [ERROR] Jurigged encountered an error
Traceback (most recent call last):
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\live.py", line 104, in refresh
    cf.refresh()
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 1118, in refresh
    new_source = self.read_source()
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 1065, in read_source
    source = f.read()
             ^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1258.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 1880: character maps to <undefined>
[11:35:13] [DEBUG] Sending data to websocket: {"op": 1, "d": 6}
[11:35:13] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[11:35:13] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[11:35:54] [DEBUG] Sending data to websocket: {"op": 1, "d": 6}
[11:35:54] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[11:35:55] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[11:36:36] [DEBUG] Sending data to websocket: {"op": 1, "d": 6}
[11:36:36] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[11:36:36] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[11:37:17] [DEBUG] Sending data to websocket: {"op": 1, "d": 6}
[11:37:17] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[11:37:17] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[11:37:24] [ERROR] Jurigged encountered an error
Traceback (most recent call last):
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\live.py", line 104, in refresh
    cf.refresh()
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 1118, in refresh
    new_source = self.read_source()
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 1065, in read_source
    source = f.read()
             ^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1258.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 1880: character maps to <undefined>
[11:37:58] [DEBUG] Sending data to websocket: {"op": 1, "d": 6}
[11:37:58] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[11:37:58] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[11:38:39] [DEBUG] Sending data to websocket: {"op": 1, "d": 6}
[11:38:39] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[11:38:40] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[11:38:43] [ERROR] Jurigged encountered an error
Traceback (most recent call last):
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\live.py", line 104, in refresh
    cf.refresh()
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 1118, in refresh
    new_source = self.read_source()
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 1065, in read_source
    source = f.read()
             ^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1258.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 1896: character maps to <undefined>
[11:38:46] [DEBUG] Dispatching Event: disconnect
[11:38:46] [DEBUG] Stopping the bot.
[11:38:46] [INFO] Shard ID 0 | Stopping Shard
