[11:56:19] [DEBUG] Running client sanity checks...
[11:56:19] [DEBUG] Loaded Extension: interactions.ext.jurigged
[11:56:19] [DEBUG] Added callback: __join
[11:56:19] [DEBUG] Added callback: __leave
[11:56:19] [DEBUG] Added callback: _about
[11:56:19] [DEBUG] Added callback: _setup
[11:56:19] [DEBUG] Added callback: on_start
[11:56:19] [DEBUG] 5 callbacks have been loaded from __main__.
[11:56:19] [DEBUG] Added callback: _disconnect
[11:56:19] [DEBUG] Added callback: _on_websocket_ready
[11:56:19] [DEBUG] Added callback: on_autocomplete_completion
[11:56:19] [DEBUG] Added callback: on_autocomplete_error
[11:56:19] [DEBUG] Added callback: on_command_completion
[11:56:19] [DEBUG] Added callback: on_command_error
[11:56:19] [DEBUG] Added callback: on_component_completion
[11:56:19] [DEBUG] Added callback: on_component_error
[11:56:19] [DEBUG] Added callback: on_error
[11:56:19] [DEBUG] Added callback: on_modal_completion
[11:56:19] [DEBUG] Added callback: on_modal_error
[11:56:19] [DEBUG] Added callback: on_resume
[11:56:19] [DEBUG] 12 callbacks have been loaded from Client.
[11:56:19] [DEBUG] Attempting to login
[11:56:20] [DEBUG] Caching ingested rate limit data for: 78bb8553d9352a5a2f89f9def401287a
[11:56:20] [DEBUG] GET /users/@me Has exhausted its ratelimit (1000)! Locking route for 0.001 seconds
[11:56:20] [DEBUG] GET /users/@me Received 200 :: [0/1000 calls remaining]
[11:56:20] [DEBUG] Caching ingested rate limit data for: d28a133af187e91d71d96a223467ce49
[11:56:20] [DEBUG] GET /oauth2/applications/@me Has exhausted its ratelimit (1000)! Locking route for 0.001 seconds
[11:56:20] [DEBUG] GET /oauth2/applications/@me Received 200 :: [0/1000 calls remaining]
[11:56:20] [WARNING] Setting sync_ext to True by default for syncing changes
[11:56:20] [INFO] Loading jurigged
[11:56:20] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\Main.py
[11:56:20] [DEBUG] GET /gateway Received 200 :: [1/1 calls remaining]
[11:56:20] [INFO] Shard ID 0 | Starting Shard
[11:56:20] [INFO] Shard ID 0 | Shard is attempting to connect to gateway...
[11:56:21] [DEBUG] Shard ID 0 | Identification payload sent to gateway, requesting intents: 3407613
[11:56:21] [INFO] Shard ID 0 | Gateway connection established
[11:56:21] [DEBUG] Shard ID 0 | Session ID: 22ae771b6baac8779ad890496ded62c6 Trace: ['["gateway-prd-us-east1-d-dnlf",{"micros":117980,"calls":["id_created",{"micros":1256,"calls":[]},"session_lookup_time",{"micros":394,"calls":[]},"session_lookup_finished",{"micros":16,"calls":[]},"discord-sessions-prd-2-12",{"micros":114941,"calls":["start_session",{"micros":51647,"calls":["discord-api-dc69f8484-kszth",{"micros":46336,"calls":["get_user",{"micros":7990},"get_guilds",{"micros":3971},"send_scheduled_deletion_message",{"micros":14},"guild_join_requests",{"micros":3758},"authorized_ip_coro",{"micros":13}]}]},"starting_guild_connect",{"micros":122,"calls":[]},"presence_started",{"micros":16830,"calls":[]},"guilds_started",{"micros":219,"calls":[]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":46088,"calls":[]},"connect_finished",{"micros":46094,"calls":[]},"build_ready",{"micros":25,"calls":[]},"clean_ready",{"micros":1,"calls":[]},"optimize_ready",{"micros":1,"calls":[]},"split_ready",{"micros":0,"calls":[]}]}]}]']
[11:56:21] [DEBUG] Dispatching Event: websocket_ready
[11:56:21] [DEBUG] Caching ingested rate limit data for: dd84d9818020c27975c0d5ab4a794d44
[11:56:21] [DEBUG] GET /applications/{application_id}/commands Has exhausted its ratelimit (1000)! Locking route for 0.001 seconds
[11:56:21] [DEBUG] GET /applications/{application_id}/commands Received 200 :: [0/1000 calls remaining]
[11:56:21] [DEBUG] Waiting for bucket dd84d9818020c27975c0d5ab4a794d44 to unlock.
[11:56:22] [DEBUG] Caching ingested rate limit data for: dd84d9818020c27975c0d5ab4a794d44
[11:56:22] [DEBUG] GET /applications/{application_id}/commands Has exhausted its ratelimit (1000)! Locking route for 0.001 seconds
[11:56:22] [DEBUG] GET /applications/{application_id}/commands Received 200 :: [0/1000 calls remaining]
[11:56:22] [DEBUG] 0 is already up-to-date with 15 commands.
[11:56:22] [DEBUG] Sync of 1 scopes took 0.7103117999940878 seconds
[11:56:22] [DEBUG] Dispatching Event: startup
[11:56:22] [DEBUG] Sending data to websocket: {"op": 3, "d": {"since": 1702961782175, "activities": [{"name": "/help for helpful", "type": 0}], "status": "idle", "afk": false}}
[11:56:23] [DEBUG] Sending heartbeat every 41.25 seconds
[11:56:23] [DEBUG] Sending data to websocket: {"op": 1, "d": 6}
[11:56:23] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[11:56:23] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[11:56:25] [DEBUG] Run __main__:21 | logger = logging.getLogger('discord_1log')
[11:56:25] [DEBUG] Delete __main__:21 | logger = logging.getLogger('discord_log')
[11:56:25] [DEBUG] Update __main__:1
[11:56:25] [DEBUG] Run __main__:21 | logger = logging.getLogger('discord_1log')
[11:56:25] [DEBUG] Delete __main__:21 | logger = logging.getLogger('discord_log')
[11:56:25] [DEBUG] Update __main__:1
[11:56:30] [DEBUG] Run __main__:21 | logger = logging.getLogger('discord_log')
[11:56:30] [DEBUG] Delete __main__:21 | logger = logging.getLogger('discord_1log')
[11:56:30] [DEBUG] Update __main__:1
[11:56:30] [DEBUG] Run __main__:21 | logger = logging.getLogger('discord_log')
[11:56:30] [DEBUG] Delete __main__:21 | logger = logging.getLogger('discord_1log')
[11:56:30] [DEBUG] Update __main__:1
[11:56:37] [DEBUG] Update __main__:1
[11:56:41] [ERROR] Jurigged encountered an error
Traceback (most recent call last):
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 480, in _process_child_correspondence
    self.evaluate_child(new)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 625, in evaluate_child
    return child.evaluate(self.get_globals(), None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 245, in evaluate
    exec(code, glb, lcl)
  File "D:\Project\Python\qpneruy-Git\music\Main.py", line 23, in <adjust>
    chào
NameError: name 'chào' is not defined
[11:56:41] [ERROR] Jurigged encountered an error
Traceback (most recent call last):
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 480, in _process_child_correspondence
    self.evaluate_child(new)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 625, in evaluate_child
    return child.evaluate(self.get_globals(), None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 245, in evaluate
    exec(code, glb, lcl)
  File "D:\Project\Python\qpneruy-Git\music\Main.py", line 23, in <adjust>
    chào
NameError: name 'chào' is not defined
[11:56:41] [DEBUG] Update __main__:1
[11:56:41] [DEBUG] Update __main__:1
[11:56:49] [DEBUG] Run __main__:23 | print("Chào")
[11:56:49] [DEBUG] Delete __main__:23 | chào
[11:56:49] [DEBUG] Delete __main__:165 | file_handler = logging.FileHandler(log_filename, encoding='utf-8')
[11:56:49] [DEBUG] Delete __main__:166 | file_handler.setLevel(logging.DEBUG)
[11:56:49] [DEBUG] Delete __main__:167 | file_handler.setFormatter(logging.Formatter(log_format, datefmt=date_format))
[11:56:49] [DEBUG] Delete __main__:170 | console_handler = logging.StreamHandler()
[11:56:49] [DEBUG] Delete __main__:171 | console_handler.setLevel(logging.DEBUG)
[11:56:49] [DEBUG] Delete __main__:172 | console_handler.setFormatter(logging.Formatter(log_format, datefmt=date_format))
[11:56:49] [DEBUG] Delete __main__:175 | logger.addHandler(file_handler)
[11:56:49] [DEBUG] Delete __main__:36 | logger.addHandler(console_handler)
[11:56:49] [DEBUG] Delete __main__:37 | """---------------------------------------------------------------------------------"""
[11:56:49] [DEBUG] Delete __main__:38 | api_key = os.getenv('YOUTUBE_API_KEY')
[11:56:49] [DEBUG] Delete __main__:39 | Token = os.getenv("Discord_Token_Bot_A")
[11:56:49] [DEBUG] Delete __main__:40 | """-----------------------------"""
[11:56:49] [DEBUG] Delete __main__:41 | bot = interactions.Client(
    intents=interactions.Intents.DEFAULT | interactions.Intents.MESSAGE_CONTENT, send_command_tracebacks=False,
    sync_interactions=True,
    asyncio_debug=True,
    logger=logger)
[11:56:49] [DEBUG] Delete __main__:46 | bot.load_extension("interactions.ext.jurigged")
[11:56:49] [DEBUG] Delete __main__:47 | """-----------------------------"""
[11:56:49] [DEBUG] Delete __main__.on_start:50
[11:56:49] [DEBUG] Delete __main__.run_batch_file:59
[11:56:49] [DEBUG] Delete __main__._about:71
[11:56:49] [DEBUG] Delete __main__.get_remaining_members:94
[11:56:49] [DEBUG] Delete __main__.__join:100
[11:56:49] [DEBUG] Delete __main__.__leave:122
[11:56:49] [DEBUG] Delete __main__._setup:141
[11:56:49] [DEBUG] Delete __main__:161 | bot.start(Token)
[11:56:49] [DEBUG] Update __main__:1
[11:56:58] [DEBUG] Delete __main__:23 | print("Chào")
[11:56:58] [DEBUG] Update __main__:1
[11:57:04] [DEBUG] Sending data to websocket: {"op": 1, "d": 6}
[11:57:04] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[11:57:04] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[11:57:17] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\play.py
[11:57:17] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\play.py
[11:57:17] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\askbard.py
[11:57:17] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\askbard.py
[11:57:18] [DEBUG] No setup function found in askbard
[11:57:18] [DEBUG] Found extension class Bard in askbard: Attempting to load
[11:57:18] [DEBUG] Added callback: Bard._askbard
[11:57:18] [DEBUG] Added callback: Bard._endbard
[11:57:18] [DEBUG] Added callback: Bard.set_bard_channel
[11:57:18] [DEBUG] Loaded Extension: askbard
[11:57:18] [DEBUG] Run __main__:155 | bot.load_extension("askbard")
[11:57:18] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\noi_chu.py
[11:57:18] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\noi_chu.py
[11:57:18] [DEBUG] No setup function found in noi_chu
[11:57:18] [DEBUG] Found extension class NoiChu in noi_chu: Attempting to load
[11:57:18] [DEBUG] Added callback: NoiChu._reset
[11:57:18] [DEBUG] Added callback: NoiChu._world_setup
[11:57:18] [DEBUG] Loaded Extension: noi_chu
[11:57:18] [DEBUG] Run __main__:156 | bot.load_extension("noi_chu")
[11:57:18] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\db_refesh.py
[11:57:18] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\db_refesh.py
[11:57:18] [DEBUG] No setup function found in db_refesh
[11:57:18] [DEBUG] Found extension class Database in db_refesh: Attempting to load
[11:57:18] [DEBUG] Loaded Extension: db_refesh
[11:57:18] [DEBUG] Run __main__:157 | bot.load_extension("db_refesh")
[11:57:18] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\help.py
[11:57:18] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\help.py
[11:57:18] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\embed.py
[11:57:18] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\embed.py
[11:57:18] [DEBUG] No setup function found in help
[11:57:18] [DEBUG] Found extension class Help in help: Attempting to load
[11:57:18] [DEBUG] Added callback: Help.help
[11:57:18] [DEBUG] Loaded Extension: help
[11:57:18] [DEBUG] Run __main__:158 | bot.load_extension("help")
[11:57:18] [DEBUG] Listener <Listener event='voice_user_join' callback=<function __join at 0x000001F96D653C40>> has already been hooked, not re-hooking it again
[11:57:18] [DEBUG] Added callback: __join
[11:57:18] [DEBUG] Listener <Listener event='voice_user_leave' callback=<function __leave at 0x000001F96D653E20>> has already been hooked, not re-hooking it again
[11:57:18] [DEBUG] Added callback: __leave
[11:57:18] [ERROR] Jurigged encountered an error
Traceback (most recent call last):
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 480, in _process_child_correspondence
    self.evaluate_child(new)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 625, in evaluate_child
    return child.evaluate(self.get_globals(), None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 245, in evaluate
    exec(code, glb, lcl)
  File "D:\Project\Python\qpneruy-Git\music\Main.py", line 160, in <adjust>
    bot.start(Token)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 993, in start
    asyncio.run(self.astart(token))
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 949, in astart
    await self.login(token)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 923, in login
    self._gather_callbacks()
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 1420, in _gather_callbacks
    process(main_commands, "__main__")
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 1406, in process
    self.add_command(func)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 1379, in add_command
    self.add_interaction(func)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 1294, in add_interaction
    raise ValueError(f"Duplicate Command! {scope}::{old_cmd.resolved_name}")
ValueError: Duplicate Command! 0::about
[11:57:18] [DEBUG] Update __main__:1
[11:57:19] [DEBUG] No setup function found in play
[11:57:19] [DEBUG] Found extension class Music in play: Attempting to load
[11:57:19] [DEBUG] Added callback: Music._menu
[11:57:19] [DEBUG] Added callback: Music._pause
[11:57:19] [DEBUG] Added callback: Music._resume
[11:57:19] [DEBUG] Added callback: Music._skip
[11:57:19] [DEBUG] Added callback: Music._stop
[11:57:19] [DEBUG] Added callback: Music.play
[11:57:19] [DEBUG] Loaded Extension: play
[11:57:19] [DEBUG] Run __main__:154 | bot.load_extension("play")
[11:57:19] [ERROR] Jurigged encountered an error
Traceback (most recent call last):
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 480, in _process_child_correspondence
    self.evaluate_child(new)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 625, in evaluate_child
    return child.evaluate(self.get_globals(), None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 245, in evaluate
    exec(code, glb, lcl)
  File "D:\Project\Python\qpneruy-Git\music\Main.py", line 155, in <adjust>
    bot.load_extension("askbard")
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 2003, in load_extension
    raise Exception(f"{module_name} already loaded")
Exception: askbard already loaded
[11:57:19] [ERROR] Jurigged encountered an error
Traceback (most recent call last):
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 480, in _process_child_correspondence
    self.evaluate_child(new)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 625, in evaluate_child
    return child.evaluate(self.get_globals(), None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 245, in evaluate
    exec(code, glb, lcl)
  File "D:\Project\Python\qpneruy-Git\music\Main.py", line 156, in <adjust>
    bot.load_extension("noi_chu")
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 2003, in load_extension
    raise Exception(f"{module_name} already loaded")
Exception: noi_chu already loaded
[11:57:19] [ERROR] Jurigged encountered an error
Traceback (most recent call last):
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 480, in _process_child_correspondence
    self.evaluate_child(new)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 625, in evaluate_child
    return child.evaluate(self.get_globals(), None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 245, in evaluate
    exec(code, glb, lcl)
  File "D:\Project\Python\qpneruy-Git\music\Main.py", line 157, in <adjust>
    bot.load_extension("db_refesh")
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 2003, in load_extension
    raise Exception(f"{module_name} already loaded")
Exception: db_refesh already loaded
[11:57:19] [ERROR] Jurigged encountered an error
Traceback (most recent call last):
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 480, in _process_child_correspondence
    self.evaluate_child(new)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 625, in evaluate_child
    return child.evaluate(self.get_globals(), None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 245, in evaluate
    exec(code, glb, lcl)
  File "D:\Project\Python\qpneruy-Git\music\Main.py", line 158, in <adjust>
    bot.load_extension("help")
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 2003, in load_extension
    raise Exception(f"{module_name} already loaded")
Exception: help already loaded
[11:57:19] [DEBUG] Update __main__:1
[11:57:26] [DEBUG] Dispatching Event: disconnect
[11:57:26] [DEBUG] Stopping the bot.
[11:57:26] [INFO] Shard ID 0 | Stopping Shard
