[16:46:11] [DEBUG] Running client sanity checks...
[16:46:11] [DEBUG] Loaded Extension: interactions.ext.jurigged
[16:46:12] [DEBUG] No setup function found in play
[16:46:12] [DEBUG] Found extension class Music in play: Attempting to load
[16:46:12] [DEBUG] Added callback: Music._menu
[16:46:12] [DEBUG] Added callback: Music._pause
[16:46:12] [DEBUG] Added callback: Music._resume
[16:46:12] [DEBUG] Added callback: Music._skip
[16:46:12] [DEBUG] Added callback: Music._stop
[16:46:12] [DEBUG] Added callback: Music.play
[16:46:12] [DEBUG] Loaded Extension: play
[16:46:13] [DEBUG] No setup function found in askbard
[16:46:13] [DEBUG] Found extension class Bard in askbard: Attempting to load
[16:46:13] [DEBUG] Added callback: Bard._askbard
[16:46:13] [DEBUG] Added callback: Bard._endbard
[16:46:13] [DEBUG] Added callback: Bard.set_bard_channel
[16:46:13] [DEBUG] Loaded Extension: askbard
[16:46:13] [DEBUG] No setup function found in noi_chu
[16:46:13] [DEBUG] Found extension class NoiChu in noi_chu: Attempting to load
[16:46:13] [DEBUG] Added callback: NoiChu._reset
[16:46:13] [DEBUG] Added callback: NoiChu._world_setup
[16:46:13] [DEBUG] Loaded Extension: noi_chu
[16:46:13] [DEBUG] No setup function found in db_refesh
[16:46:13] [DEBUG] Found extension class Database in db_refesh: Attempting to load
[16:46:13] [DEBUG] Loaded Extension: db_refesh
[16:46:13] [DEBUG] No setup function found in help
[16:46:13] [DEBUG] Found extension class Help in help: Attempting to load
[16:46:13] [DEBUG] Added callback: Help._about
[16:46:13] [DEBUG] Added callback: Help.help
[16:46:13] [DEBUG] Loaded Extension: help
[16:46:13] [DEBUG] No setup function found in channel_listen
[16:46:13] [DEBUG] Found extension class ChannelListen in channel_listen: Attempting to load
[16:46:13] [DEBUG] Added callback: ChannelListen._setup
[16:46:13] [DEBUG] Loaded Extension: channel_listen
[16:46:13] [DEBUG] Added callback: on_start
[16:46:13] [DEBUG] 1 callbacks have been loaded from __main__.
[16:46:13] [DEBUG] Added callback: _disconnect
[16:46:13] [DEBUG] Added callback: _on_websocket_ready
[16:46:13] [DEBUG] Added callback: on_autocomplete_completion
[16:46:13] [DEBUG] Added callback: on_autocomplete_error
[16:46:13] [DEBUG] Added callback: on_command_completion
[16:46:13] [DEBUG] Added callback: on_command_error
[16:46:13] [DEBUG] Added callback: on_component_completion
[16:46:13] [DEBUG] Added callback: on_component_error
[16:46:13] [DEBUG] Added callback: on_error
[16:46:13] [DEBUG] Added callback: on_modal_completion
[16:46:13] [DEBUG] Added callback: on_modal_error
[16:46:13] [DEBUG] Added callback: on_resume
[16:46:13] [DEBUG] 12 callbacks have been loaded from Client.
[16:46:13] [DEBUG] Attempting to login
[16:46:13] [DEBUG] Caching ingested rate limit data for: 78bb8553d9352a5a2f89f9def401287a
[16:46:13] [DEBUG] GET /users/@me Has exhausted its ratelimit (1000)! Locking route for 0.001 seconds
[16:46:13] [DEBUG] GET /users/@me Received 200 :: [0/1000 calls remaining]
[16:46:14] [DEBUG] Caching ingested rate limit data for: d28a133af187e91d71d96a223467ce49
[16:46:14] [DEBUG] GET /oauth2/applications/@me Has exhausted its ratelimit (1000)! Locking route for 0.001 seconds
[16:46:14] [DEBUG] GET /oauth2/applications/@me Received 200 :: [0/1000 calls remaining]
[16:46:14] [WARNING] Setting sync_ext to True by default for syncing changes
[16:46:14] [INFO] Loading jurigged
[16:46:14] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\Main.py
[16:46:14] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\play.py
[16:46:14] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\embed.py
[16:46:14] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\askbard.py
[16:46:14] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\noi_chu.py
[16:46:14] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\db_refesh.py
[16:46:14] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\help.py
[16:46:14] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\channel_listen.py
[16:46:14] [DEBUG] Caching ingested rate limit data for: 0a6d458104b103c7be293cc9b284d9ee
[16:46:14] [DEBUG] GET /gateway Received 200 :: [99/100 calls remaining]
[16:46:14] [INFO] Shard ID 0 | Starting Shard
[16:46:14] [INFO] Shard ID 0 | Shard is attempting to connect to gateway...
[16:46:14] [DEBUG] Shard ID 0 | Identification payload sent to gateway, requesting intents: 3407613
[16:46:14] [INFO] Shard ID 0 | Gateway connection established
[16:46:14] [DEBUG] Shard ID 0 | Session ID: a47728dfa1b726adb2cb4fe586115c66 Trace: ['["gateway-prd-us-east1-b-p3zk",{"micros":103852,"calls":["id_created",{"micros":1541,"calls":[]},"session_lookup_time",{"micros":287,"calls":[]},"session_lookup_finished",{"micros":17,"calls":[]},"discord-sessions-prd-2-262",{"micros":100899,"calls":["start_session",{"micros":52775,"calls":["discord-api-6c869fb97d-74nnb",{"micros":44220,"calls":["get_user",{"micros":6963},"get_guilds",{"micros":3624},"send_scheduled_deletion_message",{"micros":12},"guild_join_requests",{"micros":1026},"authorized_ip_coro",{"micros":15}]}]},"starting_guild_connect",{"micros":61,"calls":[]},"presence_started",{"micros":14815,"calls":[]},"guilds_started",{"micros":159,"calls":[]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":33056,"calls":[]},"connect_finished",{"micros":33062,"calls":[]},"build_ready",{"micros":23,"calls":[]},"clean_ready",{"micros":1,"calls":[]},"optimize_ready",{"micros":0,"calls":[]},"split_ready",{"micros":1,"calls":[]}]}]}]']
[16:46:14] [DEBUG] Dispatching Event: websocket_ready
[16:46:14] [DEBUG] Dispatching Event: guild_join
[16:46:14] [DEBUG] Dispatching Event: guild_join
[16:46:14] [DEBUG] Dispatching Event: guild_join
[16:46:14] [DEBUG] Dispatching Event: guild_join
[16:46:14] [DEBUG] Dispatching Event: guild_join
[16:46:15] [DEBUG] Caching ingested rate limit data for: dd84d9818020c27975c0d5ab4a794d44
[16:46:15] [DEBUG] GET /applications/{application_id}/commands Has exhausted its ratelimit (1000)! Locking route for 0.001 seconds
[16:46:15] [DEBUG] GET /applications/{application_id}/commands Received 200 :: [0/1000 calls remaining]
[16:46:15] [DEBUG] Waiting for bucket dd84d9818020c27975c0d5ab4a794d44 to unlock.
[16:46:15] [DEBUG] Caching ingested rate limit data for: dd84d9818020c27975c0d5ab4a794d44
[16:46:15] [DEBUG] GET /applications/{application_id}/commands Has exhausted its ratelimit (1000)! Locking route for 0.001 seconds
[16:46:15] [DEBUG] GET /applications/{application_id}/commands Received 200 :: [0/1000 calls remaining]
[16:46:15] [DEBUG] 0 is already up-to-date with 14 commands.
[16:46:15] [DEBUG] Sync of 1 scopes took 0.7026937000046019 seconds
[16:46:15] [DEBUG] Dispatching Event: startup
[16:46:15] [DEBUG] Sending data to websocket: {"op": 3, "d": {"since": 1703756775664, "activities": [{"name": "/help for helpful", "type": 0}], "status": "idle", "afk": false}}
[16:46:19] [DEBUG] 1174695146214928500::play should be called
[16:46:19] [DEBUG] Dispatching Event: message_create
[16:46:19] [DEBUG] Caching ingested rate limit data for: 432f6223265d156004ac81366c5a948f
[16:46:19] [DEBUG] POST /interactions/{interaction_id}/aW50ZXJhY3Rpb246MTE4OTg2NjkxNjk3ODkwMTA0MjpYVWFHbDJUbnNoa2tEWVozNDFjcmxiR2w2RUh5dzd4MG9DdUJSVFJKbEo2NUl2bW9hQUNDekVLUndJTVFtVmdmSU5CQ3R5QndpNzczMkNVS1djaWlUa3JZUVhuQU1SV21PNFhWdFJGMUtNazNGOTVQWjdYTm9JUmJBcjBqT0dObg/callback Received 204 :: [4/5 calls remaining]
[16:46:19] [DEBUG] Sending data to websocket: {"op": 4, "d": {"guild_id": 1067024293709496340, "channel_id": 1189851990356918383, "self_mute": false, "self_deaf": false}}
[16:46:19] [DEBUG] Waiting for voice connection data...
[16:46:19] [DEBUG] Dispatching Event: voice_user_join
[16:46:19] [DEBUG] Attempting to initialise voice gateway...
[16:46:20] [DEBUG] Voice Connection has identified itself to Voice Gateway
[16:46:20] [DEBUG] Discord send VC Ready! Establishing a socket connection...
[16:46:20] [DEBUG] IP Discovery in progress...
[16:46:20] [DEBUG] Voice Initial Response Received: b'\x00\x02\x00F\x00\x05c\x83116.100.183.123\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xfc\xfe'
[16:46:20] [DEBUG] IP Discovered: 116.100.183.123 #64766
[16:46:20] [DEBUG] Sending data to websocket: {"op": 1, "d": {"protocol": "udp", "data": {"address": "116.100.183.123", "port": 64766, "mode": "xsalsa20_poly1305_lite"}}}
[16:46:20] [DEBUG] Starting UDP Keep Alive
[16:46:20] [DEBUG] Unhandled OPCODE: 18 = data = {'user_id': '610841389164396565', 'flags': 2}
[16:46:20] [DEBUG] Unhandled OPCODE: 20 = data = {'user_id': '610841389164396565', 'platform': 0}
[16:46:20] [INFO] Voice connection established; using xsalsa20_poly1305_lite
[16:46:21] [DEBUG] Dispatching Event: command_error
[16:46:21] [DEBUG] Dispatching Event: command_completion
[16:46:21] [DEBUG] Dispatching Event: error
[16:46:21] [INFO] Command Called: play with event.ctx.args = ['https://www.youtube.com/playlist?list=PLL-LXY9dtjAYgBX0TiNDwAbgThsGBb8jD'] | event.ctx.kwargs = {'song': 'https://www.youtube.com/playlist?list=PLL-LXY9dtjAYgBX0TiNDwAbgThsGBb8jD'}
[16:46:21] [ERROR] Ignoring exception in cmd `/play`:
Traceback (most recent call last):
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 1900, in __dispatch_interaction
    response = await callback
               ^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 1771, in _run_slash_command
    return await command(ctx, **ctx.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\models\internal\command.py", line 132, in __call__
    await self.call_callback(self.callback, context)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\models\internal\application_commands.py", line 833, in call_callback
    return await self.call_with_binding(callback, ctx, *new_args, **new_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\models\internal\callback.py", line 43, in call_with_binding
    return await callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project\Python\qpneruy-Git\music\play.py", line 131, in play
    await music_queues.playlist_process(url_list)
  File "D:\Project\Python\qpneruy-Git\modules\Music_queue.py", line 39, in playlist_process
    audio = await youtube_dl.get_audio(song)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project\Python\qpneruy-Git\modules\YT_Downloader.py", line 53, in get_audio
    data = await asyncio.to_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\asyncio\threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project\Python\qpneruy-Git\modules\YT_Downloader.py", line 54, in <lambda>
    lambda: cfg_video.extract_info(url, download=False)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1556, in extract_info
    if not ie.suitable(url):
           ^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\lazy_extractors.py", line 152, in suitable
    qs = parse_qs(url)
         ^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\utils\_utils.py", line 2484, in parse_qs
    return urllib.parse.parse_qs(urllib.parse.urlparse(url).query, **kwargs)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\urllib\parse.py", line 394, in urlparse
    url, scheme, _coerce_result = _coerce_args(url, scheme)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\urllib\parse.py", line 133, in _coerce_args
    return _decode_args(args) + (_encode_result,)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\urllib\parse.py", line 117, in _decode_args
    return tuple(x.decode(encoding, errors) if x else '' for x in args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\urllib\parse.py", line 117, in <genexpr>
    return tuple(x.decode(encoding, errors) if x else '' for x in args)
                 ^^^^^^^^
AttributeError: 'coroutine' object has no attribute 'decode'

[16:46:27] [DEBUG] Sending heartbeat every 13.75 seconds
[16:46:27] [DEBUG] Sending data to websocket: {"op": 3, "d": 0.8953981089797309}
[16:46:27] [DEBUG] ❤ Voice Connection is sending Heartbeat
[16:46:27] [DEBUG] ❤ Heartbeat acknowledged after 0.07880 seconds
[16:46:29] [DEBUG] Sending heartbeat every 41.25 seconds
[16:46:29] [DEBUG] Sending data to websocket: {"op": 1, "d": 10}
[16:46:29] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[16:46:29] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[16:46:34] [DEBUG] Caching play
[16:46:34] [DEBUG] Update play.Music.play:94
[16:46:34] [DEBUG] Update play.Music:70
[16:46:34] [DEBUG] Update play.Music.play:94
[16:46:34] [DEBUG] Update play:1
[16:46:34] [DEBUG] Update play.Music:70
[16:46:34] [DEBUG] Update play:1
[16:46:34] [DEBUG] Checking play
[16:46:34] [DEBUG] Checking for changes
[16:46:34] [DEBUG] No changes detected
[16:46:38] [DEBUG] 1174695146214928500::play should be called
[16:46:39] [DEBUG] Dispatching Event: message_create
[16:46:39] [DEBUG] Caching ingested rate limit data for: 432f6223265d156004ac81366c5a948f
[16:46:39] [DEBUG] POST /interactions/{interaction_id}/aW50ZXJhY3Rpb246MTE4OTg2Njk5OTUyNjk4OTg1NDpocnQ0OFkwTlNwdmxjNEdSM2RTUjJXQkM3OG52Q1hGUUtUNU16VmtleDFtU0hhRWJ4a05SajF2aUtwNmREZzlWQ1J0dzRjYWdkb284dGQwMGVKWmRxY3lqMGFHd3FKb0NFMEloaXRoeHNNbVh4aVpiZ1pHNjJRbmxISktqOEhucw/callback Received 204 :: [4/5 calls remaining]
[16:46:40] [DEBUG] Dispatching Event: command_error
[16:46:40] [DEBUG] Dispatching Event: command_completion
[16:46:40] [DEBUG] Dispatching Event: error
[16:46:40] [INFO] Command Called: play with event.ctx.args = ['https://www.youtube.com/playlist?list=PLL-LXY9dtjAYgBX0TiNDwAbgThsGBb8jD'] | event.ctx.kwargs = {'song': 'https://www.youtube.com/playlist?list=PLL-LXY9dtjAYgBX0TiNDwAbgThsGBb8jD'}
[16:46:40] [ERROR] Ignoring exception in cmd `/play`:
Traceback (most recent call last):
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 1900, in __dispatch_interaction
    response = await callback
               ^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 1771, in _run_slash_command
    return await command(ctx, **ctx.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\models\internal\command.py", line 132, in __call__
    await self.call_callback(self.callback, context)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\models\internal\application_commands.py", line 833, in call_callback
    return await self.call_with_binding(callback, ctx, *new_args, **new_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\models\internal\callback.py", line 43, in call_with_binding
    return await callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project\Python\qpneruy-Git\music\play.py", line 130, in play
    print(items["url"])
  File "D:\Project\Python\qpneruy-Git\modules\Music_queue.py", line 39, in playlist_process
    audio = await youtube_dl.get_audio(song)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project\Python\qpneruy-Git\modules\YT_Downloader.py", line 53, in get_audio
    data = await asyncio.to_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\asyncio\threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project\Python\qpneruy-Git\modules\YT_Downloader.py", line 54, in <lambda>
    lambda: cfg_video.extract_info(url, download=False)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1556, in extract_info
    if not ie.suitable(url):
           ^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\lazy_extractors.py", line 152, in suitable
    qs = parse_qs(url)
         ^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\utils\_utils.py", line 2484, in parse_qs
    return urllib.parse.parse_qs(urllib.parse.urlparse(url).query, **kwargs)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\urllib\parse.py", line 394, in urlparse
    url, scheme, _coerce_result = _coerce_args(url, scheme)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\urllib\parse.py", line 133, in _coerce_args
    return _decode_args(args) + (_encode_result,)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\urllib\parse.py", line 117, in _decode_args
    return tuple(x.decode(encoding, errors) if x else '' for x in args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\urllib\parse.py", line 117, in <genexpr>
    return tuple(x.decode(encoding, errors) if x else '' for x in args)
                 ^^^^^^^^
AttributeError: 'coroutine' object has no attribute 'decode'

[16:46:40] [DEBUG] Sending data to websocket: {"op": 3, "d": 0.044793550235593727}
[16:46:40] [DEBUG] ❤ Voice Connection is sending Heartbeat
[16:46:40] [DEBUG] ❤ Heartbeat acknowledged after 0.08026 seconds
[16:46:54] [DEBUG] Sending data to websocket: {"op": 3, "d": 0.8495170825447347}
[16:46:54] [DEBUG] ❤ Voice Connection is sending Heartbeat
[16:46:54] [DEBUG] ❤ Heartbeat acknowledged after 0.07986 seconds
[16:47:08] [DEBUG] Sending data to websocket: {"op": 3, "d": 0.10546319802616244}
[16:47:08] [DEBUG] ❤ Voice Connection is sending Heartbeat
[16:47:08] [DEBUG] ❤ Heartbeat acknowledged after 0.09722 seconds
[16:47:10] [DEBUG] Sending data to websocket: {"op": 1, "d": 12}
[16:47:10] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[16:47:11] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[16:47:22] [DEBUG] Sending data to websocket: {"op": 3, "d": 0.1311196389203989}
[16:47:22] [DEBUG] ❤ Voice Connection is sending Heartbeat
[16:47:22] [DEBUG] ❤ Heartbeat acknowledged after 0.08019 seconds
[16:47:35] [DEBUG] Sending data to websocket: {"op": 3, "d": 0.668200648420647}
[16:47:35] [DEBUG] ❤ Voice Connection is sending Heartbeat
[16:47:36] [DEBUG] ❤ Heartbeat acknowledged after 0.10442 seconds
[16:47:36] [DEBUG] Dispatching Event: disconnect
[16:47:36] [DEBUG] Stopping the bot.
[16:47:36] [INFO] Shard ID 0 | Stopping Shard
