[14:34:00] [DEBUG] Running client sanity checks...
[14:34:00] [DEBUG] Loaded Extension: interactions.ext.jurigged
[14:34:00] [DEBUG] No setup function found in play
[14:34:00] [DEBUG] Found extension class Music in play: Attempting to load
[14:34:00] [DEBUG] Added callback: Music._menu
[14:34:00] [DEBUG] Added callback: Music._pause
[14:34:00] [DEBUG] Added callback: Music._resume
[14:34:00] [DEBUG] Added callback: Music._skip
[14:34:00] [DEBUG] Added callback: Music._skipto
[14:34:00] [DEBUG] Added callback: Music._stop
[14:34:00] [DEBUG] Added callback: Music._viewplaylist
[14:34:00] [DEBUG] Added callback: Music.play
[14:34:00] [DEBUG] Loaded Extension: play
[14:34:01] [DEBUG] No setup function found in askbard
[14:34:01] [DEBUG] Found extension class Bard in askbard: Attempting to load
[14:34:01] [DEBUG] Added callback: Bard._askbard
[14:34:01] [DEBUG] Added callback: Bard._endbard
[14:34:01] [DEBUG] Added callback: Bard.set_bard_channel
[14:34:01] [DEBUG] Loaded Extension: askbard
[14:34:01] [DEBUG] No setup function found in noi_chu
[14:34:01] [DEBUG] Found extension class NoiChu in noi_chu: Attempting to load
[14:34:01] [DEBUG] Added callback: NoiChu._reset
[14:34:01] [DEBUG] Added callback: NoiChu._world_setup
[14:34:01] [DEBUG] Loaded Extension: noi_chu
[14:34:01] [DEBUG] No setup function found in db_refesh
[14:34:01] [DEBUG] Found extension class Database in db_refesh: Attempting to load
[14:34:01] [DEBUG] Loaded Extension: db_refesh
[14:34:01] [DEBUG] No setup function found in help
[14:34:01] [DEBUG] Found extension class Help in help: Attempting to load
[14:34:01] [DEBUG] Added callback: Help._about
[14:34:01] [DEBUG] Added callback: Help.help
[14:34:01] [DEBUG] Loaded Extension: help
[14:34:01] [DEBUG] No setup function found in channel_listen
[14:34:01] [DEBUG] Found extension class ChannelListen in channel_listen: Attempting to load
[14:34:01] [DEBUG] Added callback: ChannelListen._setup
[14:34:01] [DEBUG] Loaded Extension: channel_listen
[14:34:01] [DEBUG] Added callback: on_start
[14:34:01] [DEBUG] 1 callbacks have been loaded from __main__.
[14:34:01] [DEBUG] Added callback: _disconnect
[14:34:01] [DEBUG] Added callback: _on_websocket_ready
[14:34:01] [DEBUG] Added callback: on_autocomplete_completion
[14:34:01] [DEBUG] Added callback: on_autocomplete_error
[14:34:01] [DEBUG] Added callback: on_command_completion
[14:34:01] [DEBUG] Added callback: on_command_error
[14:34:01] [DEBUG] Added callback: on_component_completion
[14:34:01] [DEBUG] Added callback: on_component_error
[14:34:01] [DEBUG] Added callback: on_error
[14:34:01] [DEBUG] Added callback: on_modal_completion
[14:34:01] [DEBUG] Added callback: on_modal_error
[14:34:01] [DEBUG] Added callback: on_resume
[14:34:01] [DEBUG] 12 callbacks have been loaded from Client.
[14:34:01] [DEBUG] Attempting to login
[14:34:02] [DEBUG] Caching ingested rate limit data for: 78bb8553d9352a5a2f89f9def401287a
[14:34:02] [DEBUG] GET /users/@me Received 200 :: [999/1000 calls remaining]
[14:34:02] [DEBUG] Caching ingested rate limit data for: d28a133af187e91d71d96a223467ce49
[14:34:02] [DEBUG] GET /oauth2/applications/@me Received 200 :: [999/1000 calls remaining]
[14:34:02] [WARNING] Setting sync_ext to True by default for syncing changes
[14:34:02] [INFO] Loading jurigged
[14:34:02] [DEBUG] Watch D:\Project\Python\qpneruy\music\Main.py
[14:34:02] [DEBUG] Watch D:\Project\Python\qpneruy\music\play.py
[14:34:02] [DEBUG] Watch D:\Project\Python\qpneruy\music\embed.py
[14:34:02] [DEBUG] Watch D:\Project\Python\qpneruy\music\askbard.py
[14:34:02] [DEBUG] Watch D:\Project\Python\qpneruy\music\noi_chu.py
[14:34:02] [DEBUG] Watch D:\Project\Python\qpneruy\music\db_refesh.py
[14:34:02] [DEBUG] Watch D:\Project\Python\qpneruy\music\help.py
[14:34:02] [DEBUG] Watch D:\Project\Python\qpneruy\music\channel_listen.py
[14:34:02] [DEBUG] Caching ingested rate limit data for: 0a6d458104b103c7be293cc9b284d9ee
[14:34:02] [DEBUG] GET /gateway Received 200 :: [99/100 calls remaining]
[14:34:02] [INFO] Shard ID 0 | Starting Shard
[14:34:02] [INFO] Shard ID 0 | Shard is attempting to connect to gateway...
[14:34:02] [DEBUG] Shard ID 0 | Identification payload sent to gateway, requesting intents: 3407613
[14:34:03] [INFO] Shard ID 0 | Gateway connection established
[14:34:03] [DEBUG] Shard ID 0 | Session ID: 6c67498817293cb9950d356d5a99733c Trace: ['["gateway-prd-us-east1-c-klz3",{"micros":113744,"calls":["id_created",{"micros":984,"calls":[]},"session_lookup_time",{"micros":267,"calls":[]},"session_lookup_finished",{"micros":14,"calls":[]},"discord-sessions-prd-2-236",{"micros":112072,"calls":["start_session",{"micros":50078,"calls":["discord-api-d6644f4b6-nnbtq",{"micros":45014,"calls":["get_user",{"micros":9330},"get_guilds",{"micros":3510},"send_scheduled_deletion_message",{"micros":9},"guild_join_requests",{"micros":956},"authorized_ip_coro",{"micros":11}]}]},"starting_guild_connect",{"micros":54,"calls":[]},"presence_started",{"micros":40599,"calls":[]},"guilds_started",{"micros":146,"calls":[]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":21167,"calls":[]},"connect_finished",{"micros":21172,"calls":[]},"build_ready",{"micros":20,"calls":[]},"clean_ready",{"micros":1,"calls":[]},"optimize_ready",{"micros":1,"calls":[]},"split_ready",{"micros":0,"calls":[]}]}]}]']
[14:34:03] [DEBUG] Dispatching Event: websocket_ready
[14:34:03] [DEBUG] Dispatching Event: guild_join
[14:34:03] [DEBUG] Dispatching Event: guild_join
[14:34:03] [DEBUG] Dispatching Event: guild_join
[14:34:03] [DEBUG] Dispatching Event: guild_join
[14:34:03] [DEBUG] Dispatching Event: guild_join
[14:34:03] [DEBUG] Dispatching Event: guild_join
[14:34:03] [DEBUG] Caching ingested rate limit data for: dd84d9818020c27975c0d5ab4a794d44
[14:34:03] [DEBUG] GET /applications/{application_id}/commands Received 200 :: [999/1000 calls remaining]
[14:34:04] [DEBUG] Caching ingested rate limit data for: dd84d9818020c27975c0d5ab4a794d44
[14:34:04] [DEBUG] GET /applications/{application_id}/commands Received 200 :: [999/1000 calls remaining]
[14:34:04] [DEBUG] 0 is already up-to-date with 16 commands.
[14:34:04] [DEBUG] Sync of 1 scopes took 0.7273343000015302 seconds
[14:34:04] [DEBUG] Dispatching Event: startup
[14:34:04] [DEBUG] Sending data to websocket: {"op": 3, "d": {"since": 1705131244158, "activities": [{"name": "/help for helpful", "type": 0}], "status": "idle", "afk": false}}
[14:34:06] [DEBUG] 1174695146214928500::play should be called
[14:34:06] [DEBUG] Dispatching Event: message_create
[14:34:06] [DEBUG] Caching ingested rate limit data for: 432f6223265d156004ac81366c5a948f
[14:34:06] [DEBUG] POST /interactions/{interaction_id}/aW50ZXJhY3Rpb246MTE5NTYzMTg0NjMzNjIzNzY1ODpkVVgwZ1pPQk9wSzdlSW12Z254UmxqbUlTYU5vMEwwa2lTSW8ya09pWXNLdE1ua2FGY1d5SUJWQVczUk5ZdERBd2w1RXYzVGMzTHZsWUhpbFc4VzZaQmNSMmRweWNoWFNrVVpoOFhTNU9XTFlHSElJeEVOVVZUQVVKN2xzTUJ4cQ/callback Received 204 :: [4/5 calls remaining]
[14:34:06] [DEBUG] Sending data to websocket: {"op": 4, "d": {"guild_id": 1067024293709496340, "channel_id": 1195571209413349428, "self_mute": false, "self_deaf": false}}
[14:34:06] [DEBUG] Waiting for voice connection data...
[14:34:06] [DEBUG] Dispatching Event: voice_user_join
[14:34:07] [DEBUG] Attempting to initialise voice gateway...
[14:34:07] [DEBUG] Voice Connection has identified itself to Voice Gateway
[14:34:07] [DEBUG] Discord send VC Ready! Establishing a socket connection...
[14:34:07] [DEBUG] IP Discovery in progress...
[14:34:07] [DEBUG] Voice Initial Response Received: b'\x00\x02\x00F\x00\x0b\xcf\x8a116.100.185.146\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xc1\xa6'
[14:34:07] [DEBUG] IP Discovered: 116.100.185.146 #49574
[14:34:07] [DEBUG] Sending data to websocket: {"op": 1, "d": {"protocol": "udp", "data": {"address": "116.100.185.146", "port": 49574, "mode": "xsalsa20_poly1305_lite"}}}
[14:34:07] [DEBUG] Starting UDP Keep Alive
[14:34:07] [DEBUG] Unhandled OPCODE: 18 = data = {'user_id': '610841389164396565', 'flags': 2}
[14:34:07] [DEBUG] Unhandled OPCODE: 20 = data = {'user_id': '610841389164396565', 'platform': 0}
[14:34:07] [INFO] Voice connection established; using xsalsa20_poly1305_lite
[14:34:12] [DEBUG] Caching ingested rate limit data for: 3d2712a9e4fe17cc9d3fed4a8e672e5f
[14:34:12] [DEBUG] PATCH /webhooks/{application_id}/aW50ZXJhY3Rpb246MTE5NTYzMTg0NjMzNjIzNzY1ODpkVVgwZ1pPQk9wSzdlSW12Z254UmxqbUlTYU5vMEwwa2lTSW8ya09pWXNLdE1ua2FGY1d5SUJWQVczUk5ZdERBd2w1RXYzVGMzTHZsWUhpbFc4VzZaQmNSMmRweWNoWFNrVVpoOFhTNU9XTFlHSElJeEVOVVZUQVVKN2xzTUJ4cQ/messages/{message_id} Received 200 :: [4/5 calls remaining]
[14:34:12] [DEBUG] Dispatching Event: message_create
[14:34:12] [DEBUG] Caching ingested rate limit data for: 3d2712a9e4fe17cc9d3fed4a8e672e5f
[14:34:12] [DEBUG] POST /webhooks/{application_id}/aW50ZXJhY3Rpb246MTE5NTYzMTg0NjMzNjIzNzY1ODpkVVgwZ1pPQk9wSzdlSW12Z254UmxqbUlTYU5vMEwwa2lTSW8ya09pWXNLdE1ua2FGY1d5SUJWQVczUk5ZdERBd2w1RXYzVGMzTHZsWUhpbFc4VzZaQmNSMmRweWNoWFNrVVpoOFhTNU9XTFlHSElJeEVOVVZUQVVKN2xzTUJ4cQ Received 200 :: [4/5 calls remaining]
[14:34:12] [DEBUG] Sending heartbeat every 41.25 seconds
[14:34:12] [DEBUG] Sending data to websocket: {"op": 1, "d": 13}
[14:34:12] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[14:34:13] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[14:34:13] [DEBUG] Dispatching Event: command_error
[14:34:13] [DEBUG] Dispatching Event: command_completion
[14:34:13] [DEBUG] Dispatching Event: error
[14:34:13] [INFO] Command Called: play with event.ctx.args = ['https://www.youtube.com/playlist?list=PLL-LXY9dtjAYkB3bVI58z3FOo8U-Bckq9'] | event.ctx.kwargs = {'song': 'https://www.youtube.com/playlist?list=PLL-LXY9dtjAYkB3bVI58z3FOo8U-Bckq9'}
[14:34:13] [ERROR] Ignoring exception in cmd `/play`:
Traceback (most recent call last):
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1581, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1716, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 718, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\youtube.py", line 4175, in _real_extract
    self.raise_no_formats(reason, expected=True)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 1196, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)
yt_dlp.utils.ExtractorError: [youtube] videoplayba: Video unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 1900, in __dispatch_interaction
    response = await callback
               ^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 1771, in _run_slash_command
    return await command(ctx, **ctx.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\models\internal\command.py", line 132, in __call__
    await self.call_callback(self.callback, context)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\models\internal\application_commands.py", line 833, in call_callback
    return await self.call_with_binding(callback, ctx, *new_args, **new_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\models\internal\callback.py", line 43, in call_with_binding
    return await callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project\Python\qpneruy\music\play.py", line 106, in play
    await music_queues.data_process(url_list, True)
  File "D:\Project\Python\qpneruy\modules\Music_queue.py", line 106, in data_process
    avatar_url = await self.VideoData.get_uploader_avt(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project\Python\qpneruy\modules\Music_queue.py", line 56, in get_uploader_avt
    data = self.youtube_dl.extract_info(url, download=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1570, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1599, in wrapper
    self.report_error(str(e), e.format_traceback())
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1048, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 987, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: [youtube] videoplayba: Video unavailable

[14:34:13] [DEBUG] Sending heartbeat every 13.75 seconds
[14:34:13] [DEBUG] Sending data to websocket: {"op": 3, "d": 0.17644652484870849}
[14:34:13] [DEBUG] ❤ Voice Connection is sending Heartbeat
[14:34:13] [DEBUG] ❤ Heartbeat acknowledged after 0.07934 seconds
[14:34:27] [DEBUG] Sending data to websocket: {"op": 3, "d": 0.7951183151393078}
[14:34:27] [DEBUG] ❤ Voice Connection is sending Heartbeat
[14:34:27] [DEBUG] ❤ Heartbeat acknowledged after 0.07065 seconds
[14:34:41] [DEBUG] Sending data to websocket: {"op": 3, "d": 0.5313937919073651}
[14:34:41] [DEBUG] ❤ Voice Connection is sending Heartbeat
[14:34:41] [DEBUG] ❤ Heartbeat acknowledged after 0.07698 seconds
[14:34:54] [DEBUG] Sending data to websocket: {"op": 1, "d": 13}
[14:34:54] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[14:34:54] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[14:34:55] [DEBUG] Sending data to websocket: {"op": 3, "d": 0.10504930957928527}
[14:34:55] [DEBUG] ❤ Voice Connection is sending Heartbeat
[14:34:55] [DEBUG] ❤ Heartbeat acknowledged after 0.07120 seconds
[14:35:08] [DEBUG] Sending data to websocket: {"op": 3, "d": 0.22673171450564922}
[14:35:08] [DEBUG] ❤ Voice Connection is sending Heartbeat
[14:35:08] [DEBUG] ❤ Heartbeat acknowledged after 0.07191 seconds
[14:35:22] [DEBUG] Sending data to websocket: {"op": 3, "d": 0.6361446150428255}
[14:35:22] [DEBUG] ❤ Voice Connection is sending Heartbeat
[14:35:22] [DEBUG] ❤ Heartbeat acknowledged after 0.07072 seconds
[14:35:29] [DEBUG] Dispatching Event: disconnect
[14:35:29] [DEBUG] Stopping the bot.
[14:35:29] [INFO] Shard ID 0 | Stopping Shard
